site_name: ToDo365 Docs
site_url: 'https://gabriel-aguiar-reis.github.io/ToDo365/'
repo_url: 'https://github.com/gabriel-aguiar-reis/ToDo365/'
repo_name: gabriel-aguiar-reis/ToDo365
edit_uri: edit/main/docs/
theme:
  features:
    - navigation.sections
  favicon: images/favicon.png
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  name: material
  palette:
    - scheme: default
      primary: grey
      toggle:
        icon: material/weather-night
        name: Modo Noturno
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Modo Claro

plugins:
    - search
    - mermaid2
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
