databases:
  - name: todo365database
    databaseName: todo365database
    user: todo365databaseuser

services:
  - type: web
    name: ToDo365
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Todo365.to_do_365.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ToDo365
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
