# Generated by Django 4.2 on 2023-04-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_with_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
