# Generated by Django 4.2 on 2023-04-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_with_calendar', '0002_usuario_validado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
